#!/bin/bash
set -e

if [ ! -x /usr/local/bin/go ]; then
    apk add gcc musl-dev go git perl linux-headers openssl
    ln -s /usr/bin /usr/lib/go

    cd /usr/local
    wget https://storage.googleapis.com/golang/go1.6.2.src.tar.gz
    tar xvzf go1.6.2.src.tar.gz
    cd go/src
    GOROOT_BOOTSTRAP=/usr/lib/go/ ./make.bash

    apk del go
    ln -s /usr/local/go/bin/go /usr/local/bin
fi
