#!/bin/bash
set -e

: ${GIT:=https://github.com/google/cadvisor.git}
: ${COMMIT:=v0.23.2}

repo_path="github.com/google/cadvisor"

cd $(dirname $0)/..

BASE=$(pwd)

export GOPATH=${BASE}/build
export PATH=${GOPATH}/bin:$PATH

mkdir -p build/src/github.com/google
cd build/src/github.com/google

go get github.com/tools/godep
go install github.com/tools/godep

if [ ! -e cadvisor ]; then
    git clone $GIT
fi

cd cadvisor
git checkout $COMMIT

VERSION=$(cat version/VERSION)

godep go build -tags netgo -installsuffix netgo --ldflags "-extldflags -static -X ${repo_path}/version.Version=$VERSION" -a github.com/google/cadvisor

mkdir -p $BASE/dist/artifacts
cp cadvisor $BASE/dist
cp $BASE/cadvisor.sh $BASE/dist
