#!/bin/bash
set -e

cd $(dirname $0)/..

CONTENT=$(cat /proc/sys/kernel/random/uuid)

rm -rf dist/artifacts

mkdir -p build/${CONTENT}
mkdir -p dist/artifacts

cp -rf apply.sh dist build/${CONTENT}

cd build

sha1sum -b $(find ${CONTENT} -type f) > ${CONTENT}/SHA1SUMS
sha1sum ${CONTENT}/SHA1SUMS > ${CONTENT}/SHA1SUMSSUM

tar czf ../dist/artifacts/cadvisor.tar.gz ${CONTENT}
